#  /$$$$$$$                                /$$       /$$                    
# | $$__  $$                              | $$      |__/                    
# | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$ | $$   /$$ /$$ /$$$$$$$   /$$$$$$ 
# | $$$$$$$  /$$__  $$ /$$__  $$ |____  $$| $$  /$$/| $$| $$__  $$ /$$__  $$
# | $$__  $$| $$  \__/| $$$$$$$$  /$$$$$$$| $$$$$$/ | $$| $$  \ $$| $$  \ $$
# | $$  \ $$| $$      | $$_____/ /$$__  $$| $$_  $$ | $$| $$  | $$| $$  | $$
# | $$$$$$$/| $$      |  $$$$$$$|  $$$$$$$| $$ \  $$| $$| $$  | $$|  $$$$$$$
# |_______/ |__/       \_______/ \_______/|__/  \__/|__/|__/  |__/ \____  $$
#                                                                  /$$  \ $$
#                                                                 |  $$$$$$/
#                                                                  \______/ 
#  /$$$$$$$                  /$$                                            
# | $$__  $$                | $$                                            
# | $$  \ $$  /$$$$$$   /$$$$$$$                                            
# | $$$$$$$  |____  $$ /$$__  $$                                            
# | $$__  $$  /$$$$$$$| $$  | $$                                            
# | $$  \ $$ /$$__  $$| $$  | $$                                            
# | $$$$$$$/|  $$$$$$$|  $$$$$$$                                            
# |_______/  \_______/ \_______/                                            
#                                                                           
#                                                                           
#                                                                           

# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 

[window]
opacity = 0.985
blur = true

[colors]
[colors.primary]
background = "#022f31"
foreground = "#ffe26a"

[colors.normal]
black   = "#022f31"
red     = "#e32535"
green   = "#2f8652"
yellow  = "#f8c120"
blue    = "#52ada8"
magenta = "#e8872e"
cyan    = "#329f85"
white   = "#ffe26a"

[colors.bright]
black   = "#2c5b34"
red     = "#ff6262"
green   = "#3db870"
yellow  = "#ffd44a"
blue    = "#63c8c2"
magenta = "#f5a050"
cyan    = "#3ec49e"
white   = "#fff384"

[colors.cursor]
text   = "#022f31"
cursor = "#ffe26a"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'