#  /$$$$$$$                                /$$       /$$                    
# | $$__  $$                              | $$      |__/                    
# | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$ | $$   /$$ /$$ /$$$$$$$   /$$$$$$ 
# | $$$$$$$  /$$__  $$ /$$__  $$ |____  $$| $$  /$$/| $$| $$__  $$ /$$__  $$
# | $$__  $$| $$  \__/| $$$$$$$$  /$$$$$$$| $$$$$$/ | $$| $$  \ $$| $$  \ $$
# | $$  \ $$| $$      | $$_____/ /$$__  $$| $$_  $$ | $$| $$  | $$| $$  | $$
# | $$$$$$$/| $$      |  $$$$$$$|  $$$$$$$| $$ \  $$| $$| $$  | $$|  $$$$$$$
# |_______/ |__/       \_______/ \_______/|__/  \__/|__/|__/  |__/ \____  $$
#                                                                  /$$  \ $$
#                                                                 |  $$$$$$/
#                                                                  \______/ 
#  /$$$$$$$                  /$$                                            
# | $$__  $$                | $$                                            
# | $$  \ $$  /$$$$$$   /$$$$$$$                                            
# | $$$$$$$  |____  $$ /$$__  $$                                            
# | $$__  $$  /$$$$$$$| $$  | $$                                            
# | $$  \ $$ /$$__  $$| $$  | $$                                            
# | $$$$$$$/|  $$$$$$$|  $$$$$$$                                            
# |_______/  \_______/ \_______/                                            
#                                                                           
#                                                                           
#                                                                           

# foot.ini
# By OldJobobo (https://github.com/OldJobobo)

[colors-dark]
background=022f31
foreground=ffe26a

regular0=022f31
regular1=e32535
regular2=2f8652
regular3=f8c120
regular4=52ada8
regular5=e8872e
regular6=329f85
regular7=ffe26a

bright0=2c5b34
bright1=ff6262
bright2=3db870
bright3=ffd44a
bright4=63c8c2
bright5=f5a050
bright6=3ec49e
bright7=fff384

#   ______   __       ______
#  /_____/\ /_/\     /_____/\
#  \:::_ \ \\:\ \    \:::_ \ \
#   \:\ \ \ \\:\ \    \:\ \ \ \
#    \:\ \ \ \\:\ \____\:\ \ \ \
#     \:\_\ \ \\:\/___/\\:\/.:| |
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
#

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'