#  /$$$$$$$                                /$$       /$$                    
# | $$__  $$                              | $$      |__/                    
# | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$ | $$   /$$ /$$ /$$$$$$$   /$$$$$$ 
# | $$$$$$$  /$$__  $$ /$$__  $$ |____  $$| $$  /$$/| $$| $$__  $$ /$$__  $$
# | $$__  $$| $$  \__/| $$$$$$$$  /$$$$$$$| $$$$$$/ | $$| $$  \ $$| $$  \ $$
# | $$  \ $$| $$      | $$_____/ /$$__  $$| $$_  $$ | $$| $$  | $$| $$  | $$
# | $$$$$$$/| $$      |  $$$$$$$|  $$$$$$$| $$ \  $$| $$| $$  | $$|  $$$$$$$
# |_______/ |__/       \_______/ \_______/|__/  \__/|__/|__/  |__/ \____  $$
#                                                                  /$$  \ $$
#                                                                 |  $$$$$$/
#                                                                  \______/ 
#  /$$$$$$$                  /$$                                            
# | $$__  $$                | $$                                            
# | $$  \ $$  /$$$$$$   /$$$$$$$                                            
# | $$$$$$$  |____  $$ /$$__  $$                                            
# | $$__  $$  /$$$$$$$| $$  | $$                                            
# | $$  \ $$ /$$__  $$| $$  | $$                                            
# | $$$$$$$/|  $$$$$$$|  $$$$$$$                                            
# |_______/  \_______/ \_______/                                            
#                                                                           
#                                                                           
#                                                                           

# hyprlock.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

$color = rgba(2, 47, 49, 1)
$inner_color = rgba(2, 47, 49, 0.66)
$outer_color = rgba(232, 135, 46, 1)
$font_color = rgba(255, 226, 106, 1)
$placeholder_color = rgba(255, 226, 106, 0.7)
$check_color = rgba(50, 159, 133, 1)

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'