#  /$$$$$$$                                /$$       /$$                    
# | $$__  $$                              | $$      |__/                    
# | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$ | $$   /$$ /$$ /$$$$$$$   /$$$$$$ 
# | $$$$$$$  /$$__  $$ /$$__  $$ |____  $$| $$  /$$/| $$| $$__  $$ /$$__  $$
# | $$__  $$| $$  \__/| $$$$$$$$  /$$$$$$$| $$$$$$/ | $$| $$  \ $$| $$  \ $$
# | $$  \ $$| $$      | $$_____/ /$$__  $$| $$_  $$ | $$| $$  | $$| $$  | $$
# | $$$$$$$/| $$      |  $$$$$$$|  $$$$$$$| $$ \  $$| $$| $$  | $$|  $$$$$$$
# |_______/ |__/       \_______/ \_______/|__/  \__/|__/|__/  |__/ \____  $$
#                                                                  /$$  \ $$
#                                                                 |  $$$$$$/
#                                                                  \______/ 
#  /$$$$$$$                  /$$                                            
# | $$__  $$                | $$                                            
# | $$  \ $$  /$$$$$$   /$$$$$$$                                            
# | $$$$$$$  |____  $$ /$$__  $$                                            
# | $$__  $$  /$$$$$$$| $$  | $$                                            
# | $$  \ $$ /$$__  $$| $$  | $$                                            
# | $$$$$$$/|  $$$$$$$|  $$$$$$$                                            
# |_______/  \_______/ \_______/                                            
#                                                                           
#                                                                           
#                                                                           

text-color=#ffe26a
border-color=#e8872e
background-color=#022f31
width=420
height=110
padding=10
border-size=2
font=Liberation Sans 11
anchor=top-right
outer-margin=20
default-timeout=5000
max-icon-size=32

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false

#  ,-----. ,--.   ,--.     ,--.       ,--.          ,--.
# '  .-.  '|  | ,-|  |     |  | ,---. |  |-.  ,---. |  |-.  ,---.
# |  | |  ||  |' .-. |,--. |  || .-. || .-. '| .-. || .-. '| .-. |
# '  '-'  '|  |\ `-' ||  '-'  /' '-' '| `-' |' '-' '| `-' |' '-' '
#  `-----' `--' `---'  `-----'  `---'  `---'  `---'  `---'  `---'